<a href="https://colab.research.google.com/github/sneh20122001/Numpy/blob/main/Basics_of_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# import library for perform task
import numpy as np

## Creating Numpy Arrays

In [ ]:
# 1D
x = np.array([11,22,33])
x


array([11, 22, 33])

In [ ]:
# 2D

y = np.array([
    [11,22,33],
    [44,55,66]
])
y

array([[11, 22, 33],
       [44, 55, 66]])

In [ ]:
# 3D

z = np.array([
    [
        [1,2,3],
        [3,2,1]
    ],
    [
        [4,5,6],
        [6,5,4]
    ]
])
z

array([[[1, 2, 3],
        [3, 2, 1]],

       [[4, 5, 6],
        [6, 5, 4]]])

## Numpy vs List

In [ ]:
# memory
p = [ i for i in range(1000000)]
import sys

sys.getsizeof(p)

8448728

In [ ]:
p = np.arange(1000000,dtype=np.int8)
sys.getsizeof(p)

1000112

In [ ]:
# speed
a = [i for i in range(1000000)]
b = [i for i in range(1000000,2000000)]

c = []
import time

start= time.time()
for i in range(len(a)):
  c.append(a[i] + b[i])
print(time.time() - start)

0.2954113483428955


In [ ]:
a = np.arange(1000000)
b = np.arange(1000000,2000000)

start = time.time()
c = a + b
print(time.time()-start)

0.008650064468383789


## Identify type of array

In [ ]:
print(x.dtype)
print(y.dtype)
print(z.dtype)

int64
int64
int64


## Change datatype

In [ ]:
a=np.array([1,2,4],dtype=float)

print(a)
print(a.dtype)


[1. 2. 4.]
float64


## Astype

In [ ]:
#convert another memory type
a.astype(np.float32)

array([1., 2., 4.], dtype=float32)

## Arange

In [ ]:
# numbers print in particular range between parameter
# first para included and last is excluded
np.arange(1,20)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

## Ndim

In [ ]:
# dimension
print(x.ndim)
print(y.ndim)
print(z.ndim)

1
2
3


## Shape and Reshape

In [ ]:
print(x.shape)
print(y.shape)
print(z.shape)

(3,)
(2, 3)
(2, 2, 3)


In [ ]:
print(x.reshape(3,1))
print(y.reshape(3,2))
print(z.reshape(2,3,2))

[[11]
 [22]
 [33]]
[[11 22]
 [33 44]
 [55 66]]
[[[1 2]
  [3 3]
  [2 1]]

 [[4 5]
  [6 6]
  [5 4]]]


## Zeros and Ones

In [ ]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

## Identity

In [ ]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Random

In [ ]:
np.random.random((3,4))

array([[0.49728331, 0.21594051, 0.1837627 , 0.02852136],
       [0.08897064, 0.79732833, 0.78362381, 0.66960886],
       [0.13642017, 0.72765453, 0.96941244, 0.5069212 ]])

## Linspace

In [ ]:
# difference between two numbers are same
np.linspace(-10,10,7,dtype=int)

array([-10,  -7,  -4,   0,   3,   6,  10])

## Size and Itemsize

In [ ]:
print(x.size)
print(y.size)
print(z.size)

3
6
12


In [ ]:
# It's depends on datatype
print(x.itemsize)
print(y.itemsize)
print(z.itemsize)

8
8
8


## Array Operations

In [ ]:
a1 = np.arange(12).reshape(3,4)
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a2 = np.arange(12,24).reshape(3,4)
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
# arithmetic +,-,*,/,%,**,//
a1 ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [ ]:
# relational ==,<,>,<=,>=,!=
a2 == 15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [ ]:
# vector operations
a1 ** a2

array([[                   0,                    1,                16384,
                    14348907],
       [          4294967296,         762939453125,      101559956668416,
           11398895185373143],
       [ 1152921504606846976, -1261475310744950487,  1864712049423024128,
         6839173302027254275]])

# Array Function

0-----------------> col

1-----------------> row

In [ ]:
# max/min/sum/prod
print(np.max(a1,axis=0))
print(np.min(a1,axis=1))
print(np.sum(a1,axis=0))
print(np.prod(a1,axis=1))

[ 8  9 10 11]
[0 4 8]
[12 15 18 21]
[   0  840 7920]


In [ ]:
# mean/median/std/var
print(np.mean(a2,axis=0))
print(np.median(a2,axis=1))
print(np.std(a2,axis=0))
print(np.var(a2,axis=1))

[16. 17. 18. 19.]
[13.5 17.5 21.5]
[3.26598632 3.26598632 3.26598632 3.26598632]
[1.25 1.25 1.25]


In [ ]:
#trigonometric functions
np.sin(a2)

array([[-0.53657292,  0.42016704,  0.99060736,  0.65028784],
       [-0.28790332, -0.96139749, -0.75098725,  0.14987721],
       [ 0.91294525,  0.83665564, -0.00885131, -0.8462204 ]])

In [ ]:
# dot product
a3 = np.arange(12).reshape(3,4)
a4 = np.arange(12,24).reshape(4,3)

np.dot(a3,a4)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [ ]:
# log and exponents
np.exp(a1)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04]])

In [ ]:
# round/floor/ceil
np.ceil(np.random.random((2,3))*100)

array([[14., 71., 28.],
       [65.,  2., 38.]])

## Sort

In [ ]:
a = np.random.randint(1,100,25)
print(a)
np.sort(a)

[ 7 48 63 64 29 37 42 42  7 84 23 12 66 83 75 44  3 92 98 40 88 81 95 57
 32]


array([ 3,  7,  7, 12, 23, 29, 32, 37, 40, 42, 42, 44, 48, 57, 63, 64, 66,
       75, 81, 83, 84, 88, 92, 95, 98])

In [ ]:
b = np.random.randint(1,100,24).reshape(6,4)
print(b)
np.sort(b,axis=0)[::-1]

[[47 38 32 16]
 [37 45  9 37]
 [40 95 17 15]
 [96 53 49 50]
 [54 71 42 47]
 [ 9 16 92 55]]


array([[96, 95, 92, 55],
       [54, 71, 49, 50],
       [47, 53, 42, 47],
       [40, 45, 32, 37],
       [37, 38, 17, 16],
       [ 9, 16,  9, 15]])

## Append

add new item



In [ ]:
np.append(a,200)

array([  7,  48,  63,  64,  29,  37,  42,  42,   7,  84,  23,  12,  66,
        83,  75,  44,   3,  92,  98,  40,  88,  81,  95,  57,  32, 200])

In [ ]:
b

array([[47, 38, 32, 16],
       [37, 45,  9, 37],
       [40, 95, 17, 15],
       [96, 53, 49, 50],
       [54, 71, 42, 47],
       [ 9, 16, 92, 55]])

In [ ]:
np.append(b,np.random.random((b.shape[0],1)),axis=1)

array([[47.        , 38.        , 32.        , 16.        ,  0.53271249],
       [37.        , 45.        ,  9.        , 37.        ,  0.69639087],
       [40.        , 95.        , 17.        , 15.        ,  0.2365388 ],
       [96.        , 53.        , 49.        , 50.        ,  0.60507953],
       [54.        , 71.        , 42.        , 47.        ,  0.59288248],
       [ 9.        , 16.        , 92.        , 55.        ,  0.42618539]])

## Concatenate

merge two array

In [ ]:
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)
print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [ ]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

## Unique

In [ ]:
e = np.array([1,1,2,2,3,4,3,4,5,5,6,6])
np.unique(e)

array([1, 2, 3, 4, 5, 6])

## Expand dims

In [ ]:
a.shape

(25,)

In [ ]:
np.expand_dims(a,axis=0).shape

(1, 25)

In [ ]:
np.expand_dims(a,axis=1).shape

(25, 1)

## Where

In [ ]:
a

array([ 7, 48, 63, 64, 29, 37, 42, 42,  7, 84, 23, 12, 66, 83, 75, 44,  3,
       92, 98, 40, 88, 81, 95, 57, 32])

In [ ]:
# a>50
np.where(a>50)

(array([ 2,  3,  9, 12, 13, 14, 17, 18, 20, 21, 22, 23]),)

In [ ]:
# replace a>50 with 0
np.where(a>50,0,a)

array([ 7, 48,  0,  0, 29, 37, 42, 42,  7,  0, 23, 12,  0,  0,  0, 44,  3,
        0,  0, 40,  0,  0,  0,  0, 32])

In [ ]:
np.where(a % 2 == 0,0,a)

array([ 7,  0, 63,  0, 29, 37,  0,  0,  7,  0, 23,  0,  0, 83, 75,  0,  3,
        0,  0,  0,  0, 81, 95, 57,  0])

# Indexing and Slicing

In [ ]:
d = np.arange(10)
e = np.arange(12).reshape(3,4)
f = np.arange(8).reshape(2,2,2)
print(d)
print(e)
print(f)

[0 1 2 3 4 5 6 7 8 9]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [ ]:
print(e[1,0])
print(f[1,0,1])
print(f[0,1,0])

4
5
2


In [ ]:
print(e[0:2,1:3])
print(f[:,1,1])
print(f[1,1,:])
print(f[:,:,1])

[[1 2]
 [5 6]]
[3 7]
[6 7]
[[1 3]
 [5 7]]


In [ ]:
# Fancy indexing
a = np.arange(24).reshape(6,4)

a[:,[0,2,3]]

array([[ 0,  2,  3],
       [ 4,  6,  7],
       [ 8, 10, 11],
       [12, 14, 15],
       [16, 18, 19],
       [20, 22, 23]])

In [ ]:
# boolean indexing
a = np.random.randint(1,100,24).reshape(6,4)
a

array([[10, 71, 32, 62],
       [98, 60, 82, 46],
       [67, 52, 99, 34],
       [10, 14, 29, 61],
       [55, 79, 34,  2],
       [22, 70, 83,  4]])

In [ ]:
# greater than 50
a[a>50]

array([71, 62, 98, 60, 82, 67, 52, 99, 61, 55, 79, 70, 83])

In [ ]:
# even number
a[a % 2 == 0]

array([10, 32, 62, 98, 60, 82, 46, 52, 34, 10, 14, 34,  2, 22, 70,  4])

In [ ]:
# grater than 50 and even number
a[(a>50) & (a%2==0)]

array([62, 98, 60, 82, 52, 70])

In [ ]:
#not  divisible by 7
a[~(a%7 == 0)]

array([10, 71, 32, 62, 60, 82, 46, 67, 52, 99, 34, 10, 29, 61, 55, 79, 34,
        2, 22, 83,  4])

## Argmax & Argmin

In [ ]:
a

array([ 7, 48, 63, 64, 29, 37, 42, 42,  7, 84, 23, 12, 66, 83, 75, 44,  3,
       92, 98, 40, 88, 81, 95, 57, 32])

In [ ]:
np.argmax(a)

18

In [ ]:
b

array([[47, 38, 32, 16],
       [37, 45,  9, 37],
       [40, 95, 17, 15],
       [96, 53, 49, 50],
       [54, 71, 42, 47],
       [ 9, 16, 92, 55]])

In [ ]:
np.argmax(b,axis=0)

array([3, 2, 5, 5])

In [ ]:
np.argmin(a)

16

## Cumsum & Cumprod

In [ ]:
a

array([ 7, 48, 63, 64, 29, 37, 42, 42,  7, 84, 23, 12, 66, 83, 75, 44,  3,
       92, 98, 40, 88, 81, 95, 57, 32])

In [ ]:
np.cumsum(a)

array([   7,   55,  118,  182,  211,  248,  290,  332,  339,  423,  446,
        458,  524,  607,  682,  726,  729,  821,  919,  959, 1047, 1128,
       1223, 1280, 1312])

In [ ]:
b

array([[47, 38, 32, 16],
       [37, 45,  9, 37],
       [40, 95, 17, 15],
       [96, 53, 49, 50],
       [54, 71, 42, 47],
       [ 9, 16, 92, 55]])

In [ ]:
np.cumsum(b,axis=1)

array([[ 47,  85, 117, 133],
       [ 37,  82,  91, 128],
       [ 40, 135, 152, 167],
       [ 96, 149, 198, 248],
       [ 54, 125, 167, 214],
       [  9,  25, 117, 172]])

In [ ]:
np.cumsum(b)

array([  47,   85,  117,  133,  170,  215,  224,  261,  301,  396,  413,
        428,  524,  577,  626,  676,  730,  801,  843,  890,  899,  915,
       1007, 1062])

In [ ]:
np.cumprod(b)

array([                  47,                 1786,                57152,
                     914432,             33833984,           1522529280,
                13702763520,         507002250240,       20280090009600,
           1926608550912000,    32752345365504000,   491285180482560000,
       -8176854894802894848, -9098195729233739776, -3089732963424010240,
       -6912695581524099072, -4350679928110317568,  4696374357229830144,
       -5666461807152201728, -8069287904219758592,  1163385156860379136,
         167418436056514560, -3044247956510212096, -1412940944675700736])

In [ ]:
b

array([[47, 38, 32, 16],
       [37, 45,  9, 37],
       [40, 95, 17, 15],
       [96, 53, 49, 50],
       [54, 71, 42, 47],
       [ 9, 16, 92, 55]])

## Percentile

In [ ]:
a

array([ 7, 48, 63, 64, 29, 37, 42, 42,  7, 84, 23, 12, 66, 83, 75, 44,  3,
       92, 98, 40, 88, 81, 95, 57, 32])

In [ ]:
np.percentile(a,50)

48.0

In [ ]:
np.median(a)

48.0

## Histogram

In [ ]:
a

array([ 7, 48, 63, 64, 29, 37, 42, 42,  7, 84, 23, 12, 66, 83, 75, 44,  3,
       92, 98, 40, 88, 81, 95, 57, 32])

In [ ]:
np.histogram(a,bins=[0,50,100])

(array([13, 12]), array([  0,  50, 100]))

## Corrcoef

In [ ]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

In [ ]:
np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

## Isin

In [ ]:
a

array([ 7, 48, 63, 64, 29, 37, 42, 42,  7, 84, 23, 12, 66, 83, 75, 44,  3,
       92, 98, 40, 88, 81, 95, 57, 32])

In [ ]:
items = [10,20,30,40,50,60,70,80,90,100]

a[np.isin(a,items)]

array([40])

## Flip

In [ ]:
a

array([ 7, 48, 63, 64, 29, 37, 42, 42,  7, 84, 23, 12, 66, 83, 75, 44,  3,
       92, 98, 40, 88, 81, 95, 57, 32])

In [ ]:
np.flip(a)

array([32, 57, 95, 81, 88, 40, 98, 92,  3, 44, 75, 83, 66, 12, 23, 84,  7,
       42, 42, 37, 29, 64, 63, 48,  7])

In [ ]:
b

array([[47, 38, 32, 16],
       [37, 45,  9, 37],
       [40, 95, 17, 15],
       [96, 53, 49, 50],
       [54, 71, 42, 47],
       [ 9, 16, 92, 55]])

In [ ]:
np.flip(b,axis=1)

array([[16, 32, 38, 47],
       [37,  9, 45, 37],
       [15, 17, 95, 40],
       [50, 49, 53, 96],
       [47, 42, 71, 54],
       [55, 92, 16,  9]])

# Put

In [ ]:
np.put(a,[0,1],[110,530])

In [ ]:
a

array([110, 530,  63,  64,  29,  37,  42,  42,   7,  84,  23,  12,  66,
        83,  75,  44,   3,  92,  98,  40,  88,  81,  95,  57,  32])

## Delete

In [ ]:
np.delete(a,[0,2,5])

array([530,  64,  29,  42,  42,   7,  84,  23,  12,  66,  83,  75,  44,
         3,  92,  98,  40,  88,  81,  95,  57,  32])

## Set Functions

In [ ]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
np.intersect1d(m,n)

array([3, 4, 5])

In [ ]:
np.setdiff1d(n,m)

array([6, 7])

In [ ]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [ ]:
m[np.in1d(m,1)]

array([1])

## Clip

In [ ]:
a

array([110, 530,  63,  64,  29,  37,  42,  42,   7,  84,  23,  12,  66,
        83,  75,  44,   3,  92,  98,  40,  88,  81,  95,  57,  32])

In [ ]:
np.clip(a,a_min=25,a_max=75)

array([75, 75, 63, 64, 29, 37, 42, 42, 25, 75, 25, 25, 66, 75, 75, 44, 25,
       75, 75, 40, 75, 75, 75, 57, 32])