<a href="https://colab.research.google.com/github/sneh20122001/Numpy/blob/main/Basics_of_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# import library for perform task
import numpy as np

## Creating Numpy Arrays

In [3]:
# 1D
x = np.array([11,22,33])
x


array([11, 22, 33])

In [4]:
# 2D

y = np.array([
    [11,22,33],
    [44,55,66]
])
y

array([[11, 22, 33],
       [44, 55, 66]])

In [5]:
# 3D

z = np.array([
    [
        [1,2,3],
        [3,2,1]
    ],
    [
        [4,5,6],
        [6,5,4]
    ]
])
z

array([[[1, 2, 3],
        [3, 2, 1]],

       [[4, 5, 6],
        [6, 5, 4]]])

## Identify type of array

In [6]:
print(x.dtype)
print(y.dtype)
print(z.dtype)

int64
int64
int64


## Change datatype

In [7]:
a=np.array([1,2,4],dtype=float)

print(a)
print(a.dtype)


[1. 2. 4.]
float64


## Astype

In [38]:
#convert another memory type
a.astype(np.float32)

array([1., 2., 4.], dtype=float32)

## Arange

In [8]:
# numbers print in particular range between parameter
# first para included and last is excluded
np.arange(1,20)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

## Ndim

In [31]:
# dimension
print(x.ndim)
print(y.ndim)
print(z.ndim)

1
2
3


## Shape and Reshape

In [9]:
print(x.shape)
print(y.shape)
print(z.shape)

(3,)
(2, 3)
(2, 2, 3)


In [10]:
print(x.reshape(3,1))
print(y.reshape(3,2))
print(z.reshape(2,3,2))

[[11]
 [22]
 [33]]
[[11 22]
 [33 44]
 [55 66]]
[[[1 2]
  [3 3]
  [2 1]]

 [[4 5]
  [6 6]
  [5 4]]]


## Zeros and Ones

In [13]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

## Identity

In [32]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Random

In [23]:
np.random.random((3,4))

array([[0.29759305, 0.57457416, 0.58921572, 0.7967248 ],
       [0.59725112, 0.42293076, 0.93595783, 0.09074245],
       [0.81928683, 0.26497229, 0.19214676, 0.95315217]])

## Linspace

In [28]:
# difference between two numbers are same
np.linspace(-10,10,7,dtype=int)

array([-10,  -7,  -4,   0,   3,   6,  10])

## Size and Itemsize

In [34]:
print(x.size)
print(y.size)
print(z.size)

3
6
12


In [36]:
# It's depends on datatype
print(x.itemsize)
print(y.itemsize)
print(z.itemsize)

8
8
8


## Array Operations

In [40]:
a1 = np.arange(12).reshape(3,4)
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [41]:
a2 = np.arange(12,24).reshape(3,4)
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [42]:
# arithmetic +,-,*,/,%,**,//
a1 ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [43]:
# relational ==,<,>,<=,>=,!=
a2 == 15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [44]:
# vector operations
a1 ** a2

array([[                   0,                    1,                16384,
                    14348907],
       [          4294967296,         762939453125,      101559956668416,
           11398895185373143],
       [ 1152921504606846976, -1261475310744950487,  1864712049423024128,
         6839173302027254275]])

# Array Function

0-----------------> col

1-----------------> row

In [47]:
# max/min/sum/prod
print(np.max(a1,axis=0))
print(np.min(a1,axis=1))
print(np.sum(a1,axis=0))
print(np.prod(a1,axis=1))

[ 8  9 10 11]
[0 4 8]
[12 15 18 21]
[   0  840 7920]


In [49]:
# mean/median/std/var
print(np.mean(a2,axis=0))
print(np.median(a2,axis=1))
print(np.std(a2,axis=0))
print(np.var(a2,axis=1))

[16. 17. 18. 19.]
[13.5 17.5 21.5]
[3.26598632 3.26598632 3.26598632 3.26598632]
[1.25 1.25 1.25]


In [50]:
#trigonometric functions
np.sin(a2)

array([[-0.53657292,  0.42016704,  0.99060736,  0.65028784],
       [-0.28790332, -0.96139749, -0.75098725,  0.14987721],
       [ 0.91294525,  0.83665564, -0.00885131, -0.8462204 ]])

In [53]:
# dot product
a3 = np.arange(12).reshape(3,4)
a4 = np.arange(12,24).reshape(4,3)

np.dot(a3,a4)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [55]:
# log and exponents
np.exp(a1)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04]])

In [58]:
# round/floor/ceil
np.ceil(np.random.random((2,3))*100)

array([[41., 23., 24.],
       [85., 53., 20.]])

# Indexing and Slicing

In [62]:
d = np.arange(10)
e = np.arange(12).reshape(3,4)
f = np.arange(8).reshape(2,2,2)
print(d)
print(e)
print(f)

[0 1 2 3 4 5 6 7 8 9]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [66]:
print(e[1,0])
print(f[1,0,1])
print(f[0,1,0])

4
5
2


In [75]:
print(e[0:2,1:3])
print(f[:,1,1])
print(f[1,1,:])
print(f[:,:,1])

[[1 2]
 [5 6]]
[3 7]
[6 7]
[[1 3]
 [5 7]]
